name = "cosmic-golf-mp"
main = "src/index.js"
compatibility_date = "2025-01-01"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "CosmicGolfRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["CosmicGolfRoom"]

[[kv_namespaces]]
binding = "GLOBAL_LB"
id = "71f643c544a64d5cb5f1c57b133c2fbb"
preview_id = "5298d2b99d3f49bbae4844fc51c24acb"
